#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "alist"
name = "AList"
description.en = "File list program that supports multiple storage"
description.fr = "Programme de liste de fichiers prenant en charge le stockage multiple"

version = "3.57.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
website = "https://alistgo.com/"
admindoc = "https://alistgo.com/guide/install/manual.html"
code = "https://github.com/AlistGo/alist"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    amd64.url = "https://github.com/AlistGo/alist/releases/download/v3.57.0/alist-linux-amd64.tar.gz"
    amd64.sha256 = "0ba5ffccf13ac7914ef4a6d75f843af43ba3ea371be6a5caac0de2331baf7a07"
    arm64.url = "https://github.com/AlistGo/alist/releases/download/v3.57.0/alist-linux-arm64.tar.gz"
    arm64.sha256 = "b1889c270d21418e8dd5f8a2f94459bab07da49a659d7f178aeb51013d6b2097"

    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "postgresql, postgresql-contrib"

    [resources.database]
    type = "postgresql"
